/**
 * Lockfile I/O utilities.
 *
 * Follows the same patterns as workspace-index-yml.ts:
 * - Atomic write via temp file + rename
 * - Defensive parsing with sanitization
 * - Graceful handling of absent files
 */

import { promises as fs } from 'fs';
import { dirname, join, resolve as pathResolve } from 'path';
import * as yaml from 'js-yaml';
import { FILE_PATTERNS } from '../constants/index.js';
import { getLocalOpenPackageDir } from './paths.js';
import { ensureDir, readTextFile } from './fs.js';
import { FileSystemError } from './errors.js';
import { logger } from './logger.js';
import { sortAndDedupeStrings } from './collections.js';
import type { Lockfile, LockfilePackage } from '../types/lockfile.js';

const CURRENT_LOCKFILE_VERSION = 1;
const LOCKFILE_HEADER = '# This file is auto-generated by opkg. Do not edit manually.';

export interface LockfileRecord {
  path: string;
  lockfile: Lockfile;
}

function emptyLockfile(): Lockfile {
  return { lockfileVersion: CURRENT_LOCKFILE_VERSION, packages: {} };
}

export function getLockfilePath(targetDir: string): string {
  return join(getLocalOpenPackageDir(targetDir), FILE_PATTERNS.OPENPACKAGE_LOCK);
}

function sanitizeLockfilePackage(entry: unknown): LockfilePackage | null {
  if (typeof entry !== 'object' || entry === null) return null;

  const raw = entry as Record<string, unknown>;
  const pkg: LockfilePackage = {};

  if (typeof raw.version === 'string' && raw.version.trim().length > 0) {
    pkg.version = raw.version.trim();
  }

  if (Array.isArray(raw.dependencies)) {
    pkg.dependencies = raw.dependencies.filter(
      (d): d is string => typeof d === 'string' && d.trim().length > 0
    );
  }

  if (typeof raw.base === 'string' && raw.base.trim().length > 0) {
    pkg.base = raw.base.trim();
  }

  if (typeof raw.path === 'string' && raw.path.trim().length > 0) {
    pkg.path = raw.path.trim();
  }

  if (typeof raw.url === 'string' && raw.url.trim().length > 0) {
    pkg.url = raw.url.trim();
  }

  if (typeof raw.ref === 'string' && raw.ref.trim().length > 0) {
    pkg.ref = raw.ref.trim();
  }

  if (typeof raw.marketplace === 'object' && raw.marketplace !== null) {
    const m = raw.marketplace as Record<string, unknown>;
    if (typeof m.url === 'string' && typeof m.commitSha === 'string' && typeof m.pluginName === 'string') {
      pkg.marketplace = { url: m.url, commitSha: m.commitSha, pluginName: m.pluginName };
    }
  }

  return pkg;
}

function sanitizeLockfileData(data: unknown): Lockfile | null {
  if (typeof data !== 'object' || data === null) return null;

  const raw = data as Record<string, unknown>;

  if (raw.lockfileVersion !== undefined && raw.lockfileVersion !== CURRENT_LOCKFILE_VERSION) {
    logger.warn(`Unsupported lockfile version: ${raw.lockfileVersion} (expected ${CURRENT_LOCKFILE_VERSION})`);
    return null;
  }

  const packagesSection = raw.packages;
  if (typeof packagesSection !== 'object' || packagesSection === null) {
    return emptyLockfile();
  }

  const packages: Record<string, LockfilePackage> = {};
  for (const [pkgName, pkgEntry] of Object.entries(packagesSection as Record<string, unknown>)) {
    if (typeof pkgName !== 'string' || pkgName.trim().length === 0) continue;
    const sanitized = sanitizeLockfilePackage(pkgEntry);
    if (sanitized) {
      packages[pkgName] = sanitized;
    }
  }

  return { lockfileVersion: CURRENT_LOCKFILE_VERSION, packages };
}

// Module-level cache keyed by resolved targetDir
const _lockfileCache = new Map<string, LockfileRecord>();

export function invalidateLockfileCache(targetDir?: string): void {
  if (targetDir) {
    _lockfileCache.delete(pathResolve(targetDir));
  } else {
    _lockfileCache.clear();
  }
}

/**
 * Read the lockfile for a workspace.
 * Results are cached per targetDir. Call invalidateLockfileCache() after writes.
 */
export async function readLockfile(targetDir: string): Promise<LockfileRecord> {
  const resolvedDir = pathResolve(targetDir);
  const cached = _lockfileCache.get(resolvedDir);
  if (cached) return cached;

  const lockfilePath = getLockfilePath(targetDir);

  try {
    const content = await readTextFile(lockfilePath);
    const parsed = yaml.load(content) as unknown;
    const sanitized = sanitizeLockfileData(parsed);
    if (!sanitized) {
      logger.warn(`Invalid lockfile detected at ${lockfilePath}, returning empty.`);
      const empty = { path: lockfilePath, lockfile: emptyLockfile() };
      _lockfileCache.set(resolvedDir, empty);
      return empty;
    }
    const result = { path: lockfilePath, lockfile: sanitized };
    _lockfileCache.set(resolvedDir, result);
    return result;
  } catch (error: any) {
    if (error?.cause?.code !== 'ENOENT' && error?.code !== 'ENOENT') {
      logger.warn(`Failed to read lockfile at ${lockfilePath}: ${error}`);
    }
    const empty = { path: lockfilePath, lockfile: emptyLockfile() };
    _lockfileCache.set(resolvedDir, empty);
    return empty;
  }
}

export async function writeLockfile(record: LockfileRecord): Promise<void> {
  const lockfilePath = record.path;
  const packages = record.lockfile.packages ?? {};

  const outputPackages: Record<string, LockfilePackage> = {};
  for (const pkgName of Object.keys(packages)) {
    const pkg = packages[pkgName];
    const out: LockfilePackage = {};

    if (pkg.version) out.version = pkg.version;
    if (pkg.dependencies && pkg.dependencies.length > 0) {
      out.dependencies = sortAndDedupeStrings(pkg.dependencies);
    }
    if (pkg.marketplace) out.marketplace = pkg.marketplace;
    if (pkg.base) out.base = pkg.base;
    if (pkg.path) out.path = pkg.path;
    if (pkg.url) out.url = pkg.url;
    if (pkg.ref) out.ref = pkg.ref;

    outputPackages[pkgName] = out;
  }

  await ensureDir(dirname(lockfilePath));

  const body = yaml.dump(
    { lockfileVersion: CURRENT_LOCKFILE_VERSION, packages: outputPackages },
    { lineWidth: 120, sortKeys: true }
  );

  const serialized = `${LOCKFILE_HEADER}\n\n${body}`;
  const tempPath = `${lockfilePath}.tmp`;
  try {
    await fs.writeFile(tempPath, serialized, 'utf8');
    await fs.rename(tempPath, lockfilePath);
    // Cache is keyed by targetDir (parent of .openpackage/); invalidate correctly
    invalidateLockfileCache(dirname(dirname(lockfilePath)));
  } catch (error) {
    try { await fs.unlink(tempPath); } catch { /* ignore cleanup error */ }
    throw new FileSystemError(`Failed to write lockfile: ${lockfilePath}`, { path: lockfilePath, error });
  }
}

export async function removeLockfileEntry(targetDir: string, packageName: string): Promise<void> {
  const record = await readLockfile(targetDir);
  if (!record.lockfile.packages[packageName]) return;

  delete record.lockfile.packages[packageName];

  // Clean stale references from other packages' dependency lists
  for (const entry of Object.values(record.lockfile.packages)) {
    if (entry.dependencies) {
      entry.dependencies = entry.dependencies.filter(d => d !== packageName);
      if (entry.dependencies.length === 0) delete entry.dependencies;
    }
  }

  await writeLockfile(record);
}
