import { build } from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const root = join(__dirname, '..');

// Read version from package.json
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));

// Generate version file before building
const generatedDir = join(root, 'src', 'generated');
mkdirSync(generatedDir, { recursive: true });
writeFileSync(
  join(generatedDir, 'version.ts'),
  `// Auto-generated by build script. Do not edit manually.\nexport const VERSION = '${pkg.version}';\n`
);

// Build with esbuild
// splitting: true ensures dynamic import() calls produce separate chunks,
// so only the invoked command's code is loaded at runtime.
await build({
  entryPoints: [join(root, 'src/index.ts')],
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'es2020',
  outdir: join(root, 'dist'),
  banner: {
    js: '#!/usr/bin/env node',
  },
  // Preserve dynamic imports as separate chunks for lazy command loading
  splitting: true,
  // Keep npm packages external (avoids CJS/ESM compat issues).
  // The project's own source is bundled; npm deps stay in node_modules.
  packages: 'external',
  sourcemap: true,
  // Tree-shake unused code
  treeShaking: true,
  // Keep readable output for debugging
  minifySyntax: true,
  minifyWhitespace: false,
  minifyIdentifiers: false,
});

console.log('Build complete: dist/');
